version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: '12.14.1'
    steps:
      - checkout
      - run:
          name: Install up
          command: curl -sf https://up.apex.sh/install | BINDIR=. sh
      - run:
          name: Install Netlify CI
          command: npm install netlify-cli -g
      - run:
          name: Setup
          command: ./setup.sh
      - run:
          name: Run Deploy Script
          command: ./deploy.sh
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy
